### ISSUE TITLE
اضافه کردن کتابخانه

### ISSUE THREAD

**Issue by zeyton1199** [muhammad-naderi/SunDatePicker#1]
سلام برای اضافه کردن این کتابخونه به پروژه چکار باید بکنم توی قسمت گردیدل هم کد رو وارد کردم اما خطا میده 
Error:(2, 0) Plugin with id 'com.novoda.bintray-release' not found.

**Comment by muhammad-naderi** [comment]
اگر امکان داره، کد 
gradle
تون رو بزارید تا بررسی کنیم

**Comment by zeyton1199** [comment]
compile 'com.github.muhammad-naderi:SunDatePicker:1.0'
البته قبلش هم فایل رو دانلود کردم و بهصورت ماژول از قسمت فایل به صورت به برنامه م اضافه کردم

**Comment by muhammad-naderi** [comment]
این خط رو هم باید اضافه کنید:

```
repositories {
        // ...
        maven { url "https://jitpack.io" }
 }
```

**Comment by zeyton1199** [comment]
سلام 
تقریبا مشکل برطرف شد اگر ممکنه در مورد فراخوانی و استفاده از این کتابخونه ی توضیحی بدید

**Comment by muhammad-naderi** [comment]
از داکیومنشن کتابخانه اصلی استفاده کنید.

https://github.com/alirezaafkar/SunDatePicker
