### ISSUE TITLE
  سلام جناب مهندس، من در انتخاب حداقل و حداکثر سالها مشکل دارم.

### ISSUE THREAD

**Issue by ali-habibi** [muhammad-naderi/SunDatePicker#2]
سلام جناب مهندس، من در انتخاب حداقل و حداکثر سالها مشکل دارم.

یک سوال :
من به این تابع هر مقداری میدم ، اعمال نمیشه...
**و فقط تقویم سال جاری را نمایش میدهد.**

dp.setYearRange(jdf.getIranianYear()-50, jdf.getIranianYear()+5)

از کجا باید حداقل و حداکثر سالها را معین کنم ، چون میخوام برای تاریخ تولد بکارگیرم.
بدجور نیاز دارم ، ممنون از راهنماییتون

**Comment by muhammad-naderi** [comment]
سلام 
ابتدا یادآوری می کنم این پروژه تنها بازنویسی پروژه آقای افکار است.
در مورد مساله ای که می فرمایید به نظر من کار می کند موضوع، برای تغییر سال، کاربر باید روی عدد سال تاچ کند تا لیست سالها را ببیند.

**Comment by ali-habibi** [comment]
سلام مهندس عزیز،
خیلی ممنون از راهنمایتون..

بله درست شد، من بخاطر محدودیت صفحه خودم سال و ماه را برداشته بودم...
و فکر میکردم ، با حرکت اسلاید تغییر میکنه...

‫در ۱۸ تیر ۱۳۹۵ ه‍.ش.، ساعت ۱۴:۰۳‏، Muhammad Naderi‏ <
notifications@github.com> نوشت:‏

> سلام
> ابتدا یادآوری می کنم این پروژه تنها بازنویسی پروژه آقای افکار است.
> در مورد مساله ای که می فرمایید به نظر من کار می کند موضوع، برای تغییر سال،
> کاربر باید روی عدد سال تاچ کند تا لیست سالها را ببیند.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/muhammad-naderi/SunDatePicker/issues/2#issuecomment-231323128,
> or mute the thread
> https://github.com/notifications/unsubscribe/ATNKzMlCF7hmxN_DzwIJTQbgi8d11kONks5qTiCEgaJpZM4JGUmt
> .

## 

_--------------------------در پناه حق..._
